### ISSUE TITLE
Neoplasm codes

### ISSUE THREAD

**Issue by vanossj** [MHubAI/SegDB#8]
Could a generic Neoplasm roi be added to SegDB? For MHubAI/models#82 and MHubAI/models#84 it would be useful to specify Neoplasm, or malignant neoplasm, but those models aren't deciding between primary and metastatic neoplasms.

The [qiicr seg json site](https://qiicr.org/dcmqi/#/seg) has the following neoplasm* labels.

|qiicr name| SCT code | SCT meaning | in SegDB |
|-|-|-|-|
| Neoplasm| [108369006](https://browser.ihtsdotools.org/?perspective=full&conceptId1=108369006&edition=MAIN/2024-08-01&release=&languages=en)| Neoplasm (morphologic abnormality)| no|
| Neoplasm, Primary | [86049000](https://browser.ihtsdotools.org/?perspective=full&conceptId1=86049000&edition=MAIN/2024-08-01&release=&languages=en)|Malignant neoplasm, primary (morphologic abnormality) | yes|
|Neoplasm, Secondary | [14799000](https://browser.ihtsdotools.org/?perspective=full&conceptId1=14799000&edition=MAIN/2024-08-01&release=&languages=en)|Neoplasm, metastatic (morphologic abnormality) | no|

I noticed that `Neoplasm, Primary` actually encodes a 'malignant' primary neoplasm, but the other codes do not specify malignancy.

Issue #4 already pointed out that the  `Neoplasm, Primary` code [86049000](https://browser.ihtsdotools.org/?perspective=full&conceptId1=86049000&edition=MAIN/2024-08-01&release=&languages=en) is outdated.

There are other codes that could specify malignant neoplasm ([1240414004](https://browser.ihtsdotools.org/?perspective=full&conceptId1=1240414004&edition=MAIN/2024-08-01&release=&languages=en&latestRedirect=false), [6219000](https://browser.ihtsdotools.org/?perspective=full&conceptId1=6219000&edition=MAIN/2024-08-01&release=&languages=en))

**Comment by LennyN95** [comment]
Yes, I agree that would be a great addition.

**Comment by LennyN95** [comment]
We now have the following three codes in SegDB: `NEOPLASM`, `NEOPLASM_MALIGNANT_PRIMARY`, `NEOPLASM_METASTATIC_SECONDARY`.
